[versions]
purefunVersion = "6.0-SNAPSHOT"
junitEngineVersion = "5.10.2"
junitPlatformVersion = "1.10.2"
versionsVersion = "0.51.0"
nexusVersion = "1.3.0"
mockitoVersion = "5.10.0"

[libraries]
purefunTypeclasses = { group = "com.github.tonivade", name = "purefun-typeclasses", version.ref = "purefunVersion" }
purefunMonad = { group = "com.github.tonivade", name = "purefun-monad", version.ref = "purefunVersion" }
purefunEffect = { group = "com.github.tonivade", name = "purefun-effect", version.ref = "purefunVersion" }
purefunInstances = { group = "com.github.tonivade", name = "purefun-instances", version.ref = "purefunVersion" }
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitEngineVersion" }
junitRunner = { group = "org.junit.platform", name = "junit-platform-runner", version.ref = "junitPlatformVersion" }
mockitoCore = { "group" = "org.mockito", name = "mockito-core", version.ref = "mockitoVersion" }
mockitoJupiter = { "group" = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockitoVersion" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsVersion" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusVersion" }