/*
 * Copyright (c) 2020, Antonio Gabriel Muñoz Conejo <antoniogmc at gmail dot com>
 * Distributed under the terms of the MIT License
 */
package com.github.tonivade.purecheck;

/**
 * 
 * @author tonivade
 *
 * @param <E> type of the error generated by the tests
 * @param <T> type of value checked by the test
 */
public class TestSpec<E, T> {

  protected final TestFactory<E, T> it = TestFactory.factory();
  
}
