package com.github.tonivade.purecheck;

/**
 * 
 * @author tonivade
 *
 * @param <E> type of the error generated by the tests
 * @param <T> type of value checked by the test
 */
public class TestSpec<E, T> {

  protected final TestFactory<String, String> it = TestFactory.factory();
  
}
